import Footer from './components/Footer'
import Nav from './components/Nav'
import { contacto } from './data/data'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
export const nav = [
  {
    text: 'Los lagos',
    href: '/'
  },
  {
    text: 'habitaciones',
    href: '/habitaciones'
  },
  {
    text: 'servicios',
    href: "/servicios"
  },
  {
    text: 'galeria',
    href: '/galeria'
  },
  {
    text: 'nosotros',
    href: '/nosotros'
  },
  {
    text: 'contacto',
    href: '/contacto'
  },
]

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={inter.className}>
        <Nav nav={nav} />
        <div className='relative mb-28 overflow-hidden '>
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
